In [2]:
import pandas as pd

In [3]:
df = pd.Series([78, 85, 92, 67, 88])

In [4]:
df

0    78
1    85
2    92
3    67
4    88
dtype: int64

In [5]:
df.values

array([78, 85, 92, 67, 88])

In [6]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
df.dtypes

dtype('int64')

In [8]:
df.mean

<bound method Series.mean of 0    78
1    85
2    92
3    67
4    88
dtype: int64>

In [9]:
df.mean()

np.float64(82.0)

In [10]:
df.max()

np.int64(92)

In [11]:
df.min()

np.int64(67)

In [12]:
data = {
    "Student": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Marks": [85, 78, 92, 74, 88]
}

In [13]:
df = pd.DataFrame(data)

In [14]:
df

  Student  Marks
0    Asha     85
1    Ravi     78
2   Meena     92
3   Kiran     74
4    Arun     88

In [15]:
df.set_index('Student', inplace=True)

In [16]:
df.loc["Meena", "Marks"]

np.int64(92)

In [17]:
data = {
    "Student": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Marks": [85, 78, 92, 74, 88],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["CSE", "ECE", "CSE", "ME", "ECE"]
}

In [18]:
df = pd.DataFrame(data)
df.set_index("Student", inplace=True)

In [19]:
df

         Marks  Age Department
Student
Asha        85   22        CSE
Ravi        78   23        ECE
Meena       92   21        CSE
Kiran       74   24         ME
Arun        88   22        ECE

In [20]:
df.head(3)

         Marks  Age Department
Student
Asha        85   22        CSE
Ravi        78   23        ECE
Meena       92   21        CSE

In [21]:
df.tail(2)

         Marks  Age Department
Student
Kiran       74   24         ME
Arun        88   22        ECE

In [22]:
df.shape

(5, 3)

In [23]:
df.columns

Index(['Marks', 'Age', 'Department'], dtype='str')

In [24]:
df.dtypes

Marks         int64
Age           int64
Department      str
dtype: object

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, Asha to Arun
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Marks       5 non-null      int64
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
dtypes: int64(2), str(1)
memory usage: 160.0+ bytes

In [26]:
df.describe()

           Marks        Age
count   5.000000   5.000000
mean   83.400000  22.400000
std     7.334848   1.140175
min    74.000000  21.000000
25%    78.000000  22.000000
50%    85.000000  22.000000
75%    88.000000  23.000000
max    92.000000  24.000000

In [27]:
df.shape[0]

5

In [28]:
df.shape[1]

3

In [29]:
df.Age

Student
Asha     22
Ravi     23
Meena    21
Kiran    24
Arun     22
Name: Age, dtype: int64

In [30]:
df.index

Index(['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun'], dtype='str', name='Student')

In [31]:
df.Marks

Student
Asha     85
Ravi     78
Meena    92
Kiran    74
Arun     88
Name: Marks, dtype: int64

In [32]:
df.iloc[0]

Marks          85
Age            22
Department    CSE
Name: Asha, dtype: object

In [33]:
df.iloc[3]

Marks         74
Age           24
Department    ME
Name: Kiran, dtype: object

In [34]:
df.iloc[0:2]

         Marks  Age Department
Student
Asha        85   22        CSE
Ravi        78   23        ECE

In [35]:
df.iloc[0:3]

         Marks  Age Department
Student
Asha        85   22        CSE
Ravi        78   23        ECE
Meena       92   21        CSE

In [36]:
df.loc[:, 'Marks']

Student
Asha     85
Ravi     78
Meena    92
Kiran    74
Arun     88
Name: Marks, dtype: int64

In [37]:
df[df['Marks']>80]

         Marks  Age Department
Student
Asha        85   22        CSE
Meena       92   21        CSE
Arun        88   22        ECE

In [38]:
df[(df['Marks']>75) & (df['Marks']<80)]

         Marks  Age Department
Student
Ravi        78   23        ECE

In [39]:
df[df['Department']=='CSE']

         Marks  Age Department
Student
Asha        85   22        CSE
Meena       92   21        CSE

In [40]:
df[(df['Marks']>80) & (df['Department']=='CSE')]

         Marks  Age Department
Student
Asha        85   22        CSE
Meena       92   21        CSE

In [41]:
df[(df['Department']=='ECE') | (df['Department']=='CSE')]

         Marks  Age Department
Student
Asha        85   22        CSE
Ravi        78   23        ECE
Meena       92   21        CSE
Arun        88   22        ECE

In [42]:
import numpy as np

In [43]:
df['Result'] = np.where(df['Marks']>75, 'Pass', 'Fail')

In [44]:
df

         Marks  Age Department Result
Student
Asha        85   22        CSE   Pass
Ravi        78   23        ECE   Pass
Meena       92   21        CSE   Pass
Kiran       74   24         ME   Fail
Arun        88   22        ECE   Pass

In [45]:
conditions = [df['Marks']>=90, df['Marks']>=80, df['Marks']>=70]

In [46]:
choices = ['A', 'B', 'C']

In [47]:
df['Grades'] = np.select(conditions, choices, default='D')

In [48]:
df

         Marks  Age Department Result Grades
Student
Asha        85   22        CSE   Pass      B
Ravi        78   23        ECE   Pass      C
Meena       92   21        CSE   Pass      A
Kiran       74   24         ME   Fail      C
Arun        88   22        ECE   Pass      B

In [49]:
df.sort_values(by='Marks')

         Marks  Age Department Result Grades
Student
Kiran       74   24         ME   Fail      C
Ravi        78   23        ECE   Pass      C
Asha        85   22        CSE   Pass      B
Arun        88   22        ECE   Pass      B
Meena       92   21        CSE   Pass      A

In [50]:
df.sort_values(by='Marks', ascending=False)

         Marks  Age Department Result Grades
Student
Meena       92   21        CSE   Pass      A
Arun        88   22        ECE   Pass      B
Asha        85   22        CSE   Pass      B
Ravi        78   23        ECE   Pass      C
Kiran       74   24         ME   Fail      C

In [51]:
df.sort_values(by=['Marks','Department'], ascending=True)

         Marks  Age Department Result Grades
Student
Kiran       74   24         ME   Fail      C
Ravi        78   23        ECE   Pass      C
Asha        85   22        CSE   Pass      B
Arun        88   22        ECE   Pass      B
Meena       92   21        CSE   Pass      A

In [96]:
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

In [97]:
students = pd.DataFrame(data)

In [98]:
students.shape

(5, 3)

In [55]:
students.isnull().sum()

Name     0
Age      1
Marks    1
dtype: int64

In [56]:
students[students.isna().any(axis=1)]

    Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

In [59]:
students.drop_duplicates()

    Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

In [60]:
stus = students.dropna()

In [62]:
stus

    Name   Age  Marks
0   Asha  22.0   85.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

In [65]:
students.fillna(students.mean(numeric_only=True))

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

In [66]:
data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

In [67]:
df2 = pd.DataFrame(data)

In [69]:
df2[df2.duplicated(keep=False)]

   Name  Marks
0  Asha     85
3  Asha     85

In [70]:
df2.drop_duplicates()

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

In [99]:
marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

In [100]:
marks.shape

(5, 2)

In [79]:
marks['Marks'].mean()

np.float64(82.0)

In [81]:
marks.min()

Student     A
Marks      67
dtype: object

In [82]:
marks.max()

Student     E
Marks      92
dtype: object

In [86]:
marks['Marks'].median()

np.float64(85.0)

In [87]:
marks['Marks'].sum()

np.int64(410)

In [88]:
marks['Marks'].std()

np.float64(9.82344135219425)

In [89]:
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)

In [92]:
df.groupby("Department")['Marks'].mean()

Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64

In [93]:
df.groupby("Department")['Marks'].max()

Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64

In [94]:
df.groupby("Department")['Marks'].count()

Department
CSE    3
ECE    2
ME     1
Name: Marks, dtype: int64

In [95]:
df.groupby("Department")['Marks'].min()

Department
CSE    80
ECE    78
ME     74
Name: Marks, dtype: int64

In [101]:
students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

In [102]:
merged_df = pd.merge(students, marks, on='StudentID')

In [103]:
merged_df

   StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

In [125]:
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)

In [126]:
df

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
6   John         ME          72        70          68
7  Priya        ECE          95        91          93

In [117]:
df[:4]

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62

In [118]:
df[:5]

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83

In [119]:
df.shape

(8, 5)

In [120]:
df['FinalMarks'].mean()

np.float64(81.625)

In [121]:
df['FinalMarks'].mean()

np.float64(81.625)

In [122]:
df.loc[df['FinalMarks'].idxmax(), 'Name']

'Meena'

In [123]:
df.loc[df['FinalMarks'].idxmin(), 'Name']

'Kiran'

In [127]:
df[df['FinalMarks']>80]

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

In [128]:
df.groupby('Department')['FinalMarks'].mean()

Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

In [129]:
df[df['Attendance']>80]

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

In [130]:
df.sort_values(by='FinalMarks')

    Name Department  Attendance  Internal  FinalMarks
3  Kiran         ME          68        65          62
6   John         ME          72        70          68
1   Ravi        ECE          75        72          74
4   Arun        ECE          82        80          83
0   Asha        CSE          92        85          88
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
2  Meena        CSE          96        94          96

In [131]:
df['Result']=np.where(df['FinalMarks']>=70, 'Pass', 'Fail')

In [132]:
df

    Name Department  Attendance  Internal  FinalMarks Result
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

In [133]:
conditions = [df['FinalMarks']>=90,df['FinalMarks']>=80, df['FinalMarks']>=70]
choices = ['Excellent', 'Very Good', 'Good']

df['Performance'] = np.select(conditions, choices, default='Needs Improvement')

In [134]:
df

,Name,Department,Attendance,Internal,FinalMarks,Result,Performance
0,Asha,CSE,92,85,88,Pass,Very Good
1,Ravi,ECE,75,72,74,Pass,Good
2,Meena,CSE,96,94,96,Pass,Excellent
3,Kiran,ME,68,65,62,Fail,Needs Improvement
4,Arun,ECE,82,80,83,Pass,Very Good
5,Divya,CSE,88,86,89,Pass,Very Good
6,John,ME,72,70,68,Fail,Needs Improvement
7,Priya,ECE,95,91,93,Pass,Excellent

In [138]:
df.groupby('Department')['FinalMarks'].max()

Department
CSE    96
ECE    93
ME     68
Name: FinalMarks, dtype: int64

In [139]:
employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})

In [140]:
df = employees

In [141]:
df['Salary'].mean()

np.float64(62875.0)

In [142]:
df['Salary'].max()

np.int64(85000)

In [143]:
df['Salary'].min()

np.int64(45000)

In [145]:
df.loc[df['Salary'].idxmax(), 'Employee']

'E06'

In [146]:
df[df['Salary']>60000]

  Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

In [149]:
df.groupby('Department')['Salary'].mean()

Department
Finance    73333.333333
HR         50000.000000
IT         61000.000000
Name: Salary, dtype: float64

In [151]:
df.groupby('Department')['Experience'].mean()

Department
Finance    5.666667
HR         4.500000
IT         4.666667
Name: Experience, dtype: float64

In [152]:
df.groupby('Department').count()

            Employee  Experience  Salary
Department
Finance            3           3       3
HR                 2           2       2
IT                 3           3       3

In [153]:
df.sort_values(by='Salary')

  Employee Department  Experience  Salary
1      E02         HR           3   45000
6      E07         IT           2   48000
4      E05         HR           6   55000
0      E01         IT           5   60000
3      E04    Finance           4   65000
7      E08    Finance           5   70000
2      E03         IT           7   75000
5      E06    Finance           8   85000

In [154]:
df[df['Experience']>3]

  Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000
3      E04    Finance           4   65000
4      E05         HR           6   55000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

In [155]:
conditions = [df['Salary']>=75000, ((df['Salary']>=50000)&(df['Salary']<=74999))]
choices = ['High', 'Medium']
df['SalaryLevel'] = np.select(conditions, choices, default='Low')

In [157]:
df

  Employee Department  Experience  Salary SalaryLevel
0      E01         IT           5   60000      Medium
1      E02         HR           3   45000         Low
2      E03         IT           7   75000        High
3      E04    Finance           4   65000      Medium
4      E05         HR           6   55000      Medium
5      E06    Finance           8   85000        High
6      E07         IT           2   48000         Low
7      E08    Finance           5   70000      Medium